extends Node
class_name ConnectionManager

@export var red_pipe_repair_rate: float = 1.0  # Red pipes generate repair value
@export var blue_pipe_resource_rate: float = 2.0 # Blue pipes generate resources

var red_connections = {}
var blue_connections = {}

func _process(delta: float):
	# Calculate repair value generated by red pipe connections
	@warning_ignore("integer_division")
	var red_pairs = red_connections.size() / 2
	if red_pairs > 0:
		GameManager.add_repair_value(red_pairs * red_pipe_repair_rate * delta)
		
	# Calculate resources generated by blue pipe connections
	@warning_ignore("integer_division")
	var blue_pairs = blue_connections.size() / 2
	if blue_pairs > 0:
		GameManager.add_resource_value(blue_pairs * blue_pipe_resource_rate * delta)

# 添加一个新的连接
func add_connection(pipe1: Pipe, pipe2: Pipe):
	var id1 = pipe1.get_instance_id()
	var id2 = pipe2.get_instance_id()
	
	# pipe_type 0 for red, 1 for blue
	var target_dict = red_connections if pipe1.pipe_type == 0 else blue_connections
	
	if not target_dict.has(id1):
		target_dict[id1] = []
	if not target_dict.has(id2):
		target_dict[id2] = []
		
	target_dict[id1].append(pipe2)
	target_dict[id2].append(pipe1)
	
	pipe1.on_connected()
	pipe2.on_connected()
	
	print("连接已注册: ", pipe1.name, " <-> ", pipe2.name)

# 移除一个连接
func remove_connection(pipe1: Pipe, pipe2: Pipe):
	var id1 = pipe1.get_instance_id()
	var id2 = pipe2.get_instance_id()

	var target_dict = red_connections if pipe1.pipe_type == 0 else blue_connections

	if target_dict.has(id1):
		target_dict[id1].erase(pipe2)
	if target_dict.has(id2):
		target_dict[id2].erase(pipe1)
		
	print("连接已移除: ", pipe1.name, " <-> ", pipe2.name)

# 获取一个管道的所有连接
func get_connections(pipe: Pipe) -> Array:
	var id = pipe.get_instance_id()
	var target_dict = red_connections if pipe.pipe_type == 0 else blue_connections
	if target_dict.has(id):
		return target_dict[id]
	return []
